# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
on:  
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  repository_dispatch:

jobs:
  workflow_run_info:
    name: Information about the workflow run
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
      - name: Show Information
        run: |
          echo "This workflow run is triggered by ${{ github.event_name }} ."
          echo " *****************************************************************************"
          echo "$GITHUB_CONTEXT"
          echo " *****************************************************************************"
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}" 
  install:
    name: "Install"
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install dependencies
        run: npm install
      - run: ls -a
      - name: Compress dependencies
        run: tar -czf node_modules.tar.gz ./node_modules
      - run: ls -a
      - name: Cache dependencies
        uses: actions/upload-artifact@v1
        with:
          name: node_modules
          path: node_modules.tar.gz
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-new-${{ hashFiles('**/package-lock.json') }}
  
  build:
    name: "Build"
    needs: install
#       - result: ['sucess']
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install dependencies
        run: npm install
      - run: ls -a
      - name: Compress dependencies
        run: tar -czf node_modules.tar.gz ./node_modules
      - run: ls -a
      - name: Cache dependencies
        uses: actions/upload-artifact@v1
        with:
          name: node_modules
          path: node_modules.tar.gz
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-new-${{ hashFiles('**/package-lock.json') }}


