# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  install:
    name: "Install"
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Setup NPM Token
      - name: Install dependencies
        run: npm install
      - run: ls -a
      - name: Compress dependencies
        run: tar -czf node_modules.tar.gz ./node_modules
      - run: ls -a
      - name: Cache dependencies
        uses: actions/upload-artifact@v1
        with:
          name: node_modules
          path: node_modules.tar.gz
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-new-${{ hashFiles('**/package-lock.json') }}

#   build:

#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [10.x, 12.x, 14.x, 15.x]
#         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

#     steps:
#     - uses: actions/checkout@v2
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v2
#       with:
#         node-version: ${{ matrix.node-version }}
#     - name: Load cached dependencies
#       uses: actions/download-artifact@v1
#       with:
#         name: node_modules
#         path: .
#     - name: Extract cache
#       run: tar -xzf node_modules.tar.gz
#     - uses: actions/cache@v2
#       with:
#         path: node_modules
#         key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
#     - run: ls -a # DEBUG
#     - run: npm run install
#     - run: npm run build --if-present
#     - run: npm test
